name: Prevent Specific File Changes on Merge

on:
  pull_request:
    branches:
      - master

jobs:
  prevent-specific-file-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global credential.helper store
        echo "machine github.com.masugata-nobumitsu login ${GITHUB_ACTOR} password ${GITHUB_TOKEN}" > ~/.netrc
        chmod 600 ~/.netrc

    - name: Check for webpack.ignore changes
      id: check_changes
      run: |
        git fetch origin
        CHANGED_FILES=$(git diff --name-only origin/master $GITHUB_SHA | grep -v "webpack.ignore" || true)
        if [ -n "$CHANGED_FILES" ]; then
          echo "changed=true" >> $GITHUB_ENV
          echo "$CHANGED_FILES" > changed_files.txt
        else
          echo "changed=false" >> $GITHUB_ENV
        fi

    - name: Prevent merge if webpack.ignore changed
      if: env.changed == 'true'
      run: |
        CHANGED_FILES=$(cat changed_files.txt)
        if [ -n "$CHANGED_FILES" ]; then
          git checkout master
          git checkout -b temp-branch
          for file in $CHANGED_FILES; do
            git checkout temp-branch -- "$file"
          done
          git add .
          git commit -m "Exclude webpack.ignore from merge" --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com.masugata-nobumitsu/test-gitattributes.git temp-branch
          echo "branch=temp-branch" >> $GITHUB_ENV
        fi
