name: Prevent Specific File Changes on Merge

on:
  pull_request:
    branches:
      - master

jobs:
  prevent-specific-file-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"

    - name: Check for webpack.ignore changes
      id: check_changes
      run: |
        git fetch origin
        CHANGED_FILES=$(git diff --name-only origin/master $GITHUB_SHA | grep -v "webpack.ignore" || true)
        if [ -n "$CHANGED_FILES" ]; then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi

    - name: Prevent merge if webpack.ignore changed
      if: env.changed == 'true'
      run: |
        git fetch origin
        CHANGED_FILES=$(git diff --name-only origin/master $GITHUB_SHA | grep -v "webpack.ignore" || true)
        git checkout master
        git checkout -b temp-branch
        xargs -I {} git checkout temp-branch -- "{}"
        git commit -m "Exclude webpack.ignore from merge" --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
        git push origin temp-branch
        echo "branch=temp-branch" >> $GITHUB_ENV
